### PR TITLE
🚀  feat(Template-store): Filter templates by sourceType

### LINKED ISSUE #642: Filter templates by `sourceType`
When creating a template, you can (but you do not have to) choose three different source types: Git, Helm repo, and OCI registry. Similar to how you can filter modules based on status, implement a filter of templates based on `sourceType`.

### PR DESCRIPTION
**Pull request by ArnavK-09**
closes #642 

## 📑 Description

image

## ✅ Checks
- [x] I have tested my code (provide screenshots or screen recordings of a working solution)
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@quest-bot loot #642

**Review by KaradzaJuraj — CHANGES_REQUESTED** [review]
Hey @ArnavK-09, thanks for picking this up.

When creating a template, choosing a `sourceType` is **optional**, meaning there can be templates with no `sourceType`.

Can you implement an additional filter for undefined `sourceType`?

**Comment by ArnavK-09** [comment]
> Hey @ArnavK-09, thanks for picking this up.
> 
> When creating a template, choosing a `sourceType` is **optional**, meaning there can be templates with no `sourceType`.
> 
> Can you implement an additional filter for undefined `sourceType`?

assuming sourceType either be empty string or undefined, i added "none" filter

**Review by KaradzaJuraj — CHANGES_REQUESTED** [review]
Hey @ArnavK-09 , I just tested this out.
The search bar and the filter by status cancel each other out.

For example:
1) I have a template `{name: "temp-1", sourceType: "git"}`, and a template `{name: "temp-2", sourceType: "helm"}`.
2) I filter to show only helm templates -> `temp-2` will appear 👍 
3) I leave the filter to show only helm templates on, but I also use the search filter and type in "temp-1" -> I expect nothing to appear, but the `temp-1` will appear and override the helm filter. 👎 

Check out how we filter in the `Modules.tsx` where you have a similar situation with module status and name search.

Also, could you rename it from "none" to "unknown" 🙏

**Comment by ArnavK-09** [comment]
> Hey @ArnavK-09 , I just tested this out. The search bar and the filter by status cancel each other out.
> 
> For example:
> 
>     1. I have a template `{name: "temp-1", sourceType: "git"}`, and a template `{name: "temp-2", sourceType: "helm"}`.
> 
>     2. I filter to show only helm templates -> `temp-2` will appear 👍
> 
>     3. I leave the filter to show only helm templates on, but I also use the search filter and type in "temp-1" -> I expect nothing to appear, but the `temp-1` will appear and override the helm filter. 👎
> 
> 
> Check out how we filter in the `Modules.tsx` where you have a similar situation with module status and name search.
> 
> Also, could you rename it from "none" to "unknown" 🙏

works fine on my side now

**Review by KaradzaJuraj — APPROVED** [review]
Thanks @ArnavK-09, this is a great addition! 🙏 🚀

**Pull request merged**
