### PR TITLE
feat(ui): add component for Secret

### LINKED ISSUE #297: Implement UI component for Secrets
**Is your feature request related to a problem? Please describe.**
Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The scope of this issue is to support `Secrets`. The new `Secrets` component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a secret by calling the backend on

```
/api/resources?group=&version=v1&kind=Secret&name=<name>&namespace=<namespace>
```

To be able to test this, you will need to use a template that supports secrets. You should add the following template and create a Module from it:
```yaml
repo: https://github.com/cyclops-ui/templates
path: redis
version: test-secrets-ui
```

### PR DESCRIPTION
**Pull request by doncicuto**
closes #297 

## 📑 Description

This PR adds a component for displaying Secrets

## ✅ Checks
- [ ] I have updated the documentation as required
- [ ] I have performed a self-review of my code

## ℹ Additional context

Here's a screenshot of the new component in action. I think that only type and dataKeys are the relevant information to be displayed.

image

### CODE REVIEW

**Comment by petar-cvit** [comment]
@doncicuto  Could we do something like this so it's easier to check the keys in a secret? You can show the type of secret outside the table.

Screenshot 2024-06-11 at 19 10 16

Values can be just `****`, but with this its more similar to how we show a configmap so it might be easier for users

**Comment by doncicuto** [comment]
Of course @petar-cvit I'll prepare these changes 

Do you want me to add a button next to the key to reveal the actual value after decoding the base64? In this case I'd need to modify the API response

**Comment by petar-cvit** [comment]
@doncicuto you can skip that for now. It would definitely be useful, but I don't want to expose cluster secrets from Cyclops since different users might have different RBAC rules and systems for handling secrets

**Comment by doncicuto** [comment]
Cool @petar-cvit I'll prepare the changes according to your needs, thanks for your feedback

**Comment by doncicuto** [comment]
Hi @petar-cvit I've added the changes that you proposed. Here's a screenshot:

image

Ready for review then

**Review by petar-cvit — APPROVED** [review]
Thanks @doncicuto!

**Pull request merged**
