### PR TITLE
feat: add status description for pods

### LINKED ISSUE #197: Add status description for pods
**Is your feature request related to a problem? Please describe.**
If a pod is not started successfully, there should be a more detailed description in the UI about why it didn't start

### PR DESCRIPTION
**Pull request by SpiffyEight77**
closes #197

## ✅ Checks
- [x] I have updated the documentation as required
- [x] I have performed a self-review of my code

### Screenshot

Screenshot 2024-07-14 at 15 23 10

### CODE REVIEW

**Review by petar-cvit — CHANGES_REQUESTED** [review]
Hey @SpiffyEight77, thanks for the PR, the tooltip you added looks great.
Would it make sense to add the tooltip to the `image` column so users can check the statues of containers independently? This way we also don't need an additional column

**Comment by SpiffyEight77** [comment]
@petar-cvit Thank you for reviewing this PR. I will remove the `status` column and add the tooltip to the `image` column later tonight. 🙇🏻‍♂️

**Comment by SpiffyEight77** [comment]
Add a tooltip with the pod description to the image column, as shown in the following screenshot.

image

**Review by petar-cvit — APPROVED** [review]
Thanks @SpiffyEight77 🧡

**Pull request merged**
