### PR TITLE
display current version

### LINKED ISSUE #143: Display Cyclops version in UI
**Is your feature request related to a problem? Please describe.**
It's always nice to display the installed version in the UI.

**Describe the solution you'd like**
Display the installed version below the "Report a bug button"

Argo does the following:
image

**Additional context**
Glasskube already supports the the v0.0.1 release, but for the user it's hard to validate that the latest version is installed.

### PR DESCRIPTION
**Pull request by petar-cvit**
resolves #143

### CODE REVIEW

**Comment by petar-cvit** [comment]
`kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/v0.0.2-rc.2/install/cyclops-install.yaml`

**Review by KaradzaJuraj — APPROVED** [review]
LGTM

**Comment by KaradzaJuraj** [comment]
Did you have something like this in mind @pmig ?
Petar pasted the `kubectl` command for this version of Cyclops in the convo above for easy testing.

**Comment by pmig** [comment]
@petar-cvit indeed looks super nice!

**Pull request merged**
