### PR TITLE
fix: area/Helm charts: Add support for Notes.txt in Helm Chart

### LINKED ISSUE #203: Ignore `Notes.txt` in Helm charts
**Describe the bug**
Helm charts can hold `Notes.txt` in their `templates` subfolder. If present, this file will break Cyclops, and the module won't be deployed.

**To Reproduce**
1. Add `Notes.txt` in the `templates` subfolder of your Helm chart 
2. Open Cyclops
3. Click on the Add New Module button and load your Helm chart
4. Try to deploy it and fail :/

**This error message might be related to the issue:**
`error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}    `

**Expected behavior**
We want Cyclops to ignore this file when deploying modules.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #203 

## Successfully deployed the template which broke Cyclops before:

image

image

image

### CODE REVIEW

**Review by petar-cvit — DISMISSED** [review]
Thanks @Sheikh-Abubaker! Also, thanks for reporting issues with running Cyclops locally

**Comment by Sheikh-Abubaker** [comment]
> Thanks @Sheikh-Abubaker! Also, thanks for reporting issues with running Cyclops locally

You're welcome @petar-cvit and also thank you!! for your help.

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker I just noticed that the notes file is actually called `NOTES.txt`. I think we should skip both NOTES.txt and Notes.txt

**Comment by Sheikh-Abubaker** [comment]
ok let me update the code and push latest changes

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit
## Tested with one of my [repo](https://github.com/Sheikh-Abubaker/cyclops-templates) this time which includes both `NOTES.txt` and `Notes.txt`.

image


image

image

**Review by petar-cvit — APPROVED** [review]
Thanks

**Pull request merged**
