### PR TITLE
extract goreleaser step

### PR DESCRIPTION
**Pull request by petar-cvit**

### CODE REVIEW

**Comment by SpiffyEight77** [comment]
Hey @petar-cvit, sorry to bother you, but it seems that GitHub Actions isn't executing the `goreleaser` step for the latest release. Is there a problem?🙇🏻‍♂️

**Comment by petar-cvit** [comment]
Hey @SpiffyEight77, goreleaser failed [here](https://github.com/cyclops-ui/cyclops/actions/runs/9438365971/job/25995307183). I guess it tries to update the latest release, but we are creating a new release in the previous step. Goreleaser then tries to update the latest release, which isn't the one we created (since it has the repo state before release creation), but the last one existing before CI started.

I separated goreleaser in a separate action that triggers on a new release so it updates the release created through the CI

**Comment by SpiffyEight77** [comment]
Hey @petar-cvit, thank you for your reply. Would you mind letting me fix it?🙇🏻‍♂️

**Comment by petar-cvit** [comment]
I think I managed to solve it, but I will test it with the next release. I'll update here when we create a new release and if everything triggered as expected

**Comment by SpiffyEight77** [comment]
OK, if there's anything I can help with, please feel free to contact me. I'll respond as soon as possible.🙇🏻‍♂️

**Pull request merged**
