### PR TITLE
🚀 feat: support to validate all templates at once one-by-one

### LINKED ISSUE #429: Implement Validate All Templates Button
In the Templates tab, each template has a `Validate` button. Once you have a lot of templates it is tedious to validate them one by one.

We should implement a `Validate all` button that will start the validation process for them all. Place the button in the lower right corner.

### PR DESCRIPTION
**Pull request by ArnavK-09**
closes #429 

## 📑 Description

button to validate all templates by just one click one by one

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

## ℹ Additional context
used async to validate one by one for better UX

(demo vid in below comment)

### CODE REVIEW

**Comment by ArnavK-09** [comment]
https://github.com/user-attachments/assets/9a43ebfe-ea88-4118-8b04-e3406b00809a

(1.5x)

**Comment by petar-cvit** [comment]
Hey @ArnavK-09, thanks for the PR, but we have already assigned people to the issues. If you want to solve an issue, you can comment on any of the open issue that is not assigned and we can assign it to you

**Comment by ArnavK-09** [comment]
> Hey @ArnavK-09, thanks for the PR, but we have already assigned people to the issues. If you want to solve an issue, you can comment on any of the open issue that is not assigned and we can assign it to you

;/ oh no i didnt saw this comment, i already made 3 prs that was assigned

**Comment by petar-cvit** [comment]
@ArnavK-09 No worries. We will wait for assigned contributors to open PRs. Can you close these for the time being so it's easier to navigate, and if needed, we can easily reopen them.

Let us know if you want to work on another issue that isn't taken

**Comment by petar-cvit** [comment]
@ArnavK-09 can you check the conflicts and resolve them?

**Comment by ArnavK-09** [comment]
> @ArnavK-09 can you check the conflicts and resolve them?

Copy, I'll do

**Comment by ArnavK-09** [comment]
@petar-cvit hey 👋 can you checkout this?

**Review by petar-cvit — CHANGES_REQUESTED** [review]
Thanks @ArnavK-09. Can we validate templates one by one instead of all at once? I'm afraid this might overload the backend, since some templates are fetched from large git repositories

**Review by petar-cvit — CHANGES_REQUESTED** [review]
Thanks, looks good. Can you put the button for validation in the table header? Its a bit out of place on the bottom

**Comment by ArnavK-09** [comment]
> Thanks, looks good. Can you put the button for validation in the table header? Its a bit out of place on the bottom

well, I placed that button after reading description of #429!

so, `put the button for validation in the table header` is this right?

image

**Comment by ArnavK-09** [comment]
or place somewhere else?

**Comment by ArnavK-09** [comment]
image

**Review by petar-cvit — CHANGES_REQUESTED** [review]
> I placed that button after reading description

Yeah, I know, but now that I see it, it looks kind of unrelated and I would not expect it there.

Can it be in the same row and to left of the `Add template reference` button and not marked as primary?

**Comment by ArnavK-09** [comment]
> > I placed that button after reading description
> 
> Yeah, I know, but now that I see it, it looks kind of unrelated and I would not expect it there.
> 
> Can it be in the same row and to left of the `Add template reference` button and not marked as primary?

image

**Comment by petar-cvit** [comment]
It looks good on the image in the comment, but the CI is failing.
```
src/components/pages/TemplateStore/TemplateStore.tsx
  Line 257:39:  Expected '===' and instead saw '=='  eqeqeq
```

**Review by petar-cvit — APPROVED** [review]
Looks good! Thanks @ArnavK-09 🧡

**Comment by ArnavK-09** [comment]
oh finally, welcome

**Pull request merged**
