### PR TITLE
🚀 feat(cyctl): Show TemplateResolvedVersion on cyctl `describe module`

### LINKED ISSUE #605: Show TemplateResolvedVersion on `cyctl describe module`
**Is your feature request related to a problem? Please describe.**
`cyctl` has a subcommand `describe` that allows you to check details about your deployed Cyclops Modules. The scope of this issue is to display `TemplateResolvedVersion` from the module state in the `cyctl describe module <module name>`.

### PR DESCRIPTION
**Pull request by ArnavK-09**
closes #605

## 📑 Description
image

## ✅ Checks
- [x] I have tested my code (provide screenshots or screen recordings of a working solution)
- [x] I have performed a self-review of my code

## ℹ Additional context
is this what expected?

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@quest-bot loot #605

**Comment by ArnavK-09** [comment]
@petar-cvit  hey, can you confirm is it what expected?

**Comment by petar-cvit** [comment]
@ArnavK-09, @s-vamshi already reached out to solve this one. When picking issues, pick the ones that nobody started working on. Also, when creating branches for new features, name them to reflect your changes.

Same goes for #608.

**Comment by ArnavK-09** [comment]
> @ArnavK-09, @s-vamshi already reached out to solve this one. When picking issues, pick the ones that nobody started working on. Also, when creating branches for new features, name them to reflect your changes.
> 
> Same goes for #608.

Oh no, i started working when it wasn't assigned to anybody, and no messages were there, I just forgot to embark it :(

That means my prs are wasted? At least #608 can be accepted if it's valid and I'll change the branch name
? What should I do

**Comment by ArnavK-09** [comment]
@petar-cvit I have changed [branch](https://github.com/ArnavK-09/cyclops/tree/feat/disable-streaming-flag-on-cyclops-ui) name, should I file pr again if it's valid instead of #608? And could it be merged as I tried :(

**Comment by petar-cvit** [comment]
@ArnavK-09, you can close these PRs and if there are no updates from the assignees, you can reopen the PRs from the new branches.

We can't merge these since others already started working on these issues. When picking issues, make sure nobody picked the issue, or if you see somebody picked the issue but there are no updates and you would like to take it, let us know, and we can figure out who to assign the issue to.

**Comment by ArnavK-09** [comment]
sad

**Pull request closed without merging**
