### PR TITLE
feat: deploy modules to different namespaces

### LINKED ISSUE #201: Enable deploying Modules in Different Namespaces
Modules is a CRD created by Cyclops. It represents your applications and services in the Kubernetes cluster. Currently, all modules are deployed in the `cyclops` namespace. This is displayed under the module name when opening the module details page

We want Cyclops to be able to deploy modules in any namespace.

### PR DESCRIPTION
**Pull request by hanshal101**
CLOSES #201
FIXES #201 

## 📑 Description
In this PR I have added  the functionality to deploy modules to different namespace

## ✅ Checks
- [ ] I have updated the documentation as required
- [ ] I have performed a self-review of my code

## ℹ Screenshots
image

- Here you can see `test-ns-module` deployed in `test` namespace
image

### CODE REVIEW

**Comment by petar-cvit** [comment]
Hey @hanshal101, what do you think about adding a collapsible section for other options? We could put the namespace option there, but also some other stuff for the future. It will hold all the options for deploying a module besides the name of the module and  the values

**Comment by hanshal101** [comment]
Cool will do this

**Comment by hanshal101** [comment]
Hey i'm not able to find and figure how can this be done, can you please help me with this?

**Comment by hanshal101** [comment]
image
Something like this works?

**Comment by petar-cvit** [comment]
Instead of Module namespace, you can just have a [Collapse](https://ant.design/components/collapse) that can be called `options` or something and inside you can set your namespace

**Comment by hanshal101** [comment]
image
Like this?

**Comment by petar-cvit** [comment]
You can add options directly under name and remove the `Define Module` title

**Comment by hanshal101** [comment]
Ohk so the options should render the items?

**Comment by petar-cvit** [comment]
No, I'd have the title `Module name` and under it name field and `options` collapse. Under that title `Define Module` which will have all the fields from the template rendered under it

**Comment by hanshal101** [comment]
image
Just for confirmation

**Comment by petar-cvit** [comment]
Yup, that looks good. Can you make the options the same width as the name field?

**Comment by hanshal101** [comment]
I think I messed something here
Can you please help

**Pull request closed without merging**
