### PR TITLE
Fix: updated the displaying of the namespace 

### LINKED ISSUE #599: `cyctl get resources` missing namespace
`cyctl` implements a `get resource <module name>` subcommand, which prints Kubernetes resources deployed from a Module.

The scope of the issue is to print the namespace of the deployed resources for a more clear overview of the resources.

### PR DESCRIPTION
**Pull request by Abiji-2020**
closes #599 

## 📑 Description

In the command line `cyctl get resources`  updated to display the Namespace of the deployed modules. 

## ✅ Checks
- [x] I have tested my code (provide screenshots or screen recordings of a working solution)
- [x] I have performed a self-review of my code

## ℹ Additional context

@quest-bot loot #599

image

### CODE REVIEW

**Comment by Abiji-2020** [comment]
@quest-bot loot #599

**Comment by Abiji-2020** [comment]
@petar-cvit any reviews on the PR?

**Review by petar-cvit — CHANGES_REQUESTED** [review]
I tried it on a module created from the rabbitmq template and the output was the following

```
./cyctl get resources rabbit
KIND                 NAME                 NAMESPACE
Secret               rabbit-rabbitmq     default
Secret               rabbit-rabbitmq-configdefault
Service              rabbit-rabbitmq     default
Service              rabbit-rabbitmq-headlessdefault
ServiceAccount       rabbit-rabbitmq     default
StatefulSet          rabbit-rabbitmq     default
NetworkPolicy        rabbit-rabbitmq     default
PodDisruptionBudget  rabbit-rabbitmq     default
Role                 rabbit-rabbitmq-endpoint-readerdefault
RoleBinding          rabbit-rabbitmq-endpoint-readerdefault
```

Can you replace `name` and `namespace` columns? Also make sure to calculate the longest value in the column so you know how much space is needed between columns (in the example above name and namespace columns are not properly separated).

**Comment by Abiji-2020** [comment]
# After  updating 
image

**Review by petar-cvit — APPROVED** [review]
Thanks @Abiji-2020 🧡  Looks much more simple

**Comment by Abiji-2020** [comment]
@petar-cvit could you approve the reward for this quest ?

**Pull request merged**
