### PR TITLE
Modify Cyclops CRDs creation command

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
closes #

## ✅ Checks
- [ ] I have updated the documentation as required
- [ ] I have performed a self-review of my code

## ℹ Additional context

This PR Modifies CRD command to create Cyclops CRDs in cyclops namespace instead of default.

### CODE REVIEW

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit When working on a issue or testing features in local system I have to explicitly define everytime to create Cyclops CRDs at cyclops namespace, to resolve that I opened this PR, hope it'll be helpful for others too!

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, could you check again if that was the issue? The `kubectl apply` you changed created CRD, which are non namespaced resources, so the `-n` flag would not change anything.

Is there some other command that needs to be fixed?

**Comment by Sheikh-Abubaker** [comment]
> The `kubectl apply` you changed created CRD, which are non namespaced resources, so the `-n` flag would not change anything.

> isn't the CRDs supposed to be created in cyclops namespace ?

**Comment by Sheikh-Abubaker** [comment]
> Hey @Sheikh-Abubaker, could you check again if that was the issue? The `kubectl apply` you changed created CRD, which are non namespaced resources, so the `-n` flag would not change anything.
> 
> Is there some other command that needs to be fixed?

Sorry sorry my bad, I think I got confused for a moment

**Comment by petar-cvit** [comment]
No worries. Just to be clear, CRDs are Custom Resource __Definitions__ and, as such, just define how other Custom Resources need to be defined. In Cyclops case, you will have Module CRD, which will be deployed on cluster scope since it extends K8s API, but your Module `demo` (Custom Resource) will be deployed in the `cyclops` namespace so cyclops-ctrl can pick it up.

Closing this one then.

**Pull request closed without merging**
